### ISSUE TITLE
Cannot compile Freetype library

### ISSUE THREAD

**Issue by K1LL34** [rrath/Wire3D#1]
I am using Msys2, and I was compiling when I got the following:
"make[1]: Entering directory '/usr/local/Wire3D/Tools/freetype'
/opt/devkitpro/devkitPPC/bin/powerpc-eabi-gcc   -I. -I./builds/wii -I./include -c -DFT2_BUILD_LIBRARY -DFT_CONFIG_MODULES_H="<ftmodule.h>"  -o ftsystem.o src/base/ftsystem.c
make[1]: *** [builds/freetype.mk:198: ftsystem.o] Error 1
make[1]: Leaving directory '/usr/local/Wire3D/Tools/freetype'
make: *** [Makefile:8: all] Error 2"

I am confused, since I am not a wizard with make.

**Comment by K1LL34** [comment]
The first error seems to be from line 198 of freetype.mk.

"$(FT_COMPILE) $T$(subst /,$(COMPILER_SEP),$@ $<)"

**Comment by rrath** [comment]
Seems like gcc is throwing an error while trying to compile ftsystem.c. FreeType is a third party lib that I am not affiliated with in any way. Can you successfully build other WiiBrew projects that use FreeType?

**Comment by K1LL34** [comment]
Since this is not an error of this project, I will close this issue.  Other than that, I found some precompiled Freetype libs, and the engine and samples compiled correctly.  Anyways, this is a fantastic project with lots of useful functionality, and there seems to be no bugs in sight.  I am sorry for the misunderstanding.

**Comment by iyenal** [comment]
@K1LL34 I am having the same issue, can you please send your precompiled libs you're using? Thanks in advance. (Using one of mine throws other issues concerning PNG bzip2 compression)
Nevermind, happened that MSYS Pacman package installer didn't installed ppc-freetype in the right location, so I have used the Resource Monitor to find it and move it.
