### ISSUE TITLE
Can't build Data (.idx .nm .uv0 .uv1 ... files)

### ISSUE THREAD

**Issue by Fewnity** [rrath/Wire3D#2]
Hello, I have a problem in the Game/Demo d'amples Or one of my samples.
It's looks like Data's folder files are not included in the game build... I think the MakeFile doesn't build these files.
Can you help me please?
I tried to add the folder in the list of target folders of Makefile like
DATA			:=	../../Data

But now in my CMD I have this error :

make[1]: *** No rule to make target 'Cube.idx.o', needed by '/opt/devkitpro/Wire3D-master/Samples/SampleTest/builds/gcc_wii/SampleTest.elf'.  Stop.

Thank you!

**Comment by Fewnity** [comment]
And I cant run the demo/game sample on Dolphin. The emulator crashes...
But the windows build version works...

**Comment by rrath** [comment]
I have never used the emulator, but a Wii with the Homebrew channel, where data must be copied manually to the SD card into the same directory as the *.dol executable.

**Comment by Fewnity** [comment]
Ho yeah I tried to create a virtual SD card on the emulator and it's works!
Thanks!
I will try this on a real Nintendo WII later ^^
