### ISSUE TITLE
Spline used in the demo

### ISSUE THREAD

**Issue by h3xstream** [rrath/Wire3D#7]
I was wondering which tool was used to **produce the spline** where the camera is attached in the demo.

https://github.com/rrath/Wire3D/blob/14ac3850deb861c4ae2b0464251f6f5e41e0e786/Samples/Demo/Data/scene.xml#L357-L360

I am unsure if this is a 3rd party package or a built-in feature from Unity.

**Comment by rrath** [comment]
> I am unsure if this is a 3rd party package or a built-in feature from Unity.

There was no tool involved. I manually placed a couple of nodes directly in the Unity scene. These nodes serve as the control points for the spline. I wrote a simple script calculating the same spline and applying it to the Unity camera, so I could prototype the camera fly-through in Unity directly.

**Comment by h3xstream** [comment]
Thanks @rrath
I recreated something similar with [`FantasticSplines`](https://github.com/AntonyJBlackett/Spline/tree/master). (Script extracting points from the FantasticSplines component and generating a similar XML.)

![spline_unity](https://github.com/rrath/Wire3D/assets/593130/e56fab84-084d-4cb8-bae5-29ba10ee9430)

Also, I noticed also that the main camera from the scene needs to be disabled (`Enable="0"`) for the SplineCamera to be triggered.

So far, it seems to mostly work but I need to figure out how to calculate the proper rotation for each position.
https://youtu.be/JxmVQ6qy_c8

**Comment by h3xstream** [comment]
I think I got what I needed.
